# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 670f69ae16baf923f429988342c2d1dac75c0c4c9173ca6ed8e68609b8f5b01d55964a60f0103f40c756b4e7b9442fd63d2bc61a303a4c164117978c07217476

test:
  secret_key_base: 096d8f5ff8e1de803d34429cc92c1095a88a1e66e92116ea2b379a80f066d7aee42ce3a7d7854723049fdf3e536e59741b0793b51e257ec46787d98707ec5523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
